language: python
sdffkhl:sdf:sdfds:sdfsdF:sdsd
fsfSF:sdFsf;lsdjflkfasdfaf
afa
python:
#  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get install swig
install: pip install --allow-all-external -r requirements.txt
script: python tests/test.py unit
cache: true
